<?php 
$title = 'Панель управления сайтом - Настройки кэширования рейтинга';
require_once('../Sys/head.php');
reg();
level(2);
echo '<div class="title">Настройка кэширования статистики</div>';
if(!isset($_POST['ok']))
	{
		$checkIndex0 = $cache['indexStats'] == 0 ? 'checked' : '';
		$checkIndex1 = $cache['indexStats'] == 1 ? 'checked' : '';
		$checkAll0 = $cache['allStats'] == 0 ? 'checked' : '';
		$checkAll1 = $cache['allStats'] == 1 ? 'checked' : '';
		$checkHours0 = $cache['hoursStats'] == 0 ? 'checked' : '';
		$checkHours1 = $cache['hoursStats'] == 1 ? 'checked' : '';
		$checkMonth0 = $cache['monthStats'] == 0 ? 'checked' : '';
		$checkMonth1 = $cache['monthStats'] == 1 ? 'checked' : '';
		$checkDays0 = $cache['daysStats'] == 0 ? 'checked' : '';
		$checkDays1 = $cache['daysStats'] == 1 ? 'checked' : '';
		$checkOperators0 = $cache['operatorsStats'] == 0 ? 'checked' : '';
		$checkOperators1 = $cache['operatorsStats'] == 1 ? 'checked' : '';
		$checkOnline0 = $cache['onlineStats'] == 0 ? 'checked' : '';
		$checkOnline1 = $cache['onlineStats'] == 1 ? 'checked' : '';
		$checkBrowsers0 = $cache['browsersStats'] == 0 ? 'checked' : '';
		$checkBrowsers1 = $cache['browsersStats'] == 1 ? 'checked' : '';
		$checkCompression0 = $cache['compressionStats'] == 0 ? 'checked' : '';
		$checkCompression1 = $cache['compressionStats'] == 1 ? 'checked' : '';
		$checkCountry0 = $cache['countryStats'] == 0 ? 'checked' : '';
		$checkCountry1 = $cache['countryStats'] == 1 ? 'checked' : '';
		$checkAllTop0 = $cache['AllTopStats'] == 0 ? 'checked' : '';
		$checkAllTop1 = $cache['AllTopStats'] == 1 ? 'checked' : '';
		echo '<div class="main">';
		echo '<form action="" method="post" name="form">';
		echo 'Кэшировать информацию о сайте:<br/>';
		echo '<input type="radio" '.$checkIndex1.' name="indexStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkIndex0.' name="indexStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать общую статистику:<br/>';
		echo '<input type="radio" '.$checkAll1.' name="allStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkAll0.' name="allStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по часам:<br/>';
		echo '<input type="radio" '.$checkHours1.' name="hoursStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkHours0.' name="hoursStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по месяцам:<br/>';
		echo '<input type="radio" '.$checkMonth1.' name="monthStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkMonth0.' name="monthStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по дням:<br/>';
		echo '<input type="radio" '.$checkDays1.' name="daysStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkDays0.' name="daysStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по операторам:<br/>';
		echo '<input type="radio" '.$checkOperators1.' name="operatorsStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkOperators0.' name="operatorsStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по онлайн:<br/>';
		echo '<input type="radio" '.$checkOnline1.' name="onlineStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkOnline0.' name="onlineStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по браузерам:<br/>';
		echo '<input type="radio" '.$checkBrowsers1.' name="browsersStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkBrowsers0.' name="browsersStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по сжатию:<br/>';
		echo '<input type="radio" '.$checkCompression1.' name="compressionStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkCompression0.' name="compressionStats" class="button" value="0"/>Нет<br/>';
		echo 'Кэшировать статистику по странам:<br/>';
		echo '<input type="radio" '.$checkCountry1.' name="countryStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkCountry0.' name="countryStats" class="button" value="0"/>Нет<br/>';
		echo '<hr>';
		echo 'Кэшировать <strong>Полную статистику рейтинга</strong>:<br/>';
		echo '<input type="radio" '.$checkAllTop1.' name="AllTopStats" class="button" value="1"/>Да<br/>';
		echo '<input type="radio" '.$checkAllTop0.' name="AllTopStats" class="button" value="0"/>Нет<br/>';
		echo '<input name="ok" type="submit" class="button" value="Сохранить" /></form></div>';
	}	
else
	{
		$indexStats = abs(intval($_POST['indexStats']));
		$allStats = abs(intval($_POST['allStats']));
		$hoursStats = abs(intval($_POST['hoursStats']));
		$monthStats = abs(intval($_POST['monthStats']));
		$daysStats = abs(intval($_POST['daysStats']));
		$operatorsStats = abs(intval($_POST['operatorsStats']));
		$onlineStats = abs(intval($_POST['onlineStats']));
		$browsersStats = abs(intval($_POST['browsersStats']));
		$compressionStats = abs(intval($_POST['compressionStats']));
		$countryStats = abs(intval($_POST['countryStats']));
		$AllTopStats = abs(intval($_POST['AllTopStats']));
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$indexStats."' WHERE `name` = 'indexStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$allStats."' WHERE `name` = 'allStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$hoursStats."' WHERE `name` = 'hoursStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$monthStats."' WHERE `name` = 'monthStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$daysStats."' WHERE `name` = 'daysStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$operatorsStats."' WHERE `name` = 'operatorsStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$onlineStats."' WHERE `name` = 'onlineStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$browsersStats."' WHERE `name` = 'browsersStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$compressionStats."' WHERE `name` = 'compressionStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$countryStats."' WHERE `name` = 'countryStats'");
		$mysqli->query("UPDATE `".$prefix."cacheSettings` SET `value` = '".$AllTopStats."' WHERE `name` = 'AllTopStats'");
		echo '<div class="main">';
		echo 'Настройки успешно изменены.<br/>';
		echo '</div>';
	}
echo '<hr/>';
echo '<div class="main">';
echo '<a href="http://'.$_SERVER['HTTP_HOST'].'/controlPanel/cacheSettings">К управлению настройками кэша</a><br/>';
echo '<a href="http://'.$_SERVER['HTTP_HOST'].'/controlPanel">В Админку</a><br/>';
echo '</div>';
?>